name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"

permissions:
  contents: write

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Draw keymap
        uses: caksoylar/keymap-drawer@main
        with:
          kmap_filename: config/sofle.keymap
          config_path: keymap_drawer.config.yaml
          output_folder: keymap-drawer
          parse_args: "--base-keymap zmk"

      - name: Commit updated images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update keymap svg [skip ci]"
          file_pattern: keymap-drawer/*.svg